name: Build Debug android-json-rpc-client

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
        cache: gradle
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
         cmdline-tools-version: 8512546
    - run: |
           sdkmanager --install "build-tools;23.0.2"
           sdkmanager --install "platform-tools"
           sdkmanager --install "platforms;android-23"
           
    - name: Grant execute permission for gradlew
      run: |
            cd RPC-ANDROID
            chmod +x gradlew
      
    - name: Build with Gradle
      run: | 
            sudo apt-get install lib32z1
            cd RPC-ANDROID
            ls -l
            ./gradlew assembleDebug
    - uses: actions/upload-artifact@v4
      with:
        name: Build Debug android-json-rpc-client
        path: |
               RPC-ANDROID/app/build/outputs/apk/app-debug.apk
            
